/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAdvocateReportByDateRouteImport } from './routes/dashboard/advocate/reportByDate'
import { Route as DashboardAdvocateReportByFormRouteImport } from './routes/dashboard/advocate/reportByForm'
import { Route as DashboardFormSalesFormSalesRouteImport } from './routes/dashboard/formSales/formSales'
import { Route as DashboardFormSalesFormSalesReportRouteImport } from './routes/dashboard/formSales/formSalesReport'
import { Route as DashboardReportSalesFormReportByAdvocateIdRouteImport } from './routes/dashboard/report/salesFormReportByAdvocateId'
import { Route as DashboardReportSalesFormReportBycategoryRouteImport } from './routes/dashboard/report/salesFormReportBycategory'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardSettingsAllAdvocatesRouteImport } from './routes/dashboard/settings/allAdvocates'
import { Route as DashboardSettingsCreateUserRouteImport } from './routes/dashboard/settings/createUser'
import { Route as DashboardSettingsFormCategoryRouteImport } from './routes/dashboard/settings/formCategory'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdvocateReportByDateRoute =
  DashboardAdvocateReportByDateRouteImport.update({
    id: '/advocate/reportByDate',
    path: '/advocate/reportByDate',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdvocateReportByFormRoute =
  DashboardAdvocateReportByFormRouteImport.update({
    id: '/advocate/reportByForm',
    path: '/advocate/reportByForm',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFormSalesFormSalesRoute =
  DashboardFormSalesFormSalesRouteImport.update({
    id: '/formSales/formSales',
    path: '/formSales/formSales',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFormSalesFormSalesReportRoute =
  DashboardFormSalesFormSalesReportRouteImport.update({
    id: '/formSales/formSalesReport',
    path: '/formSales/formSalesReport',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportSalesFormReportByAdvocateIdRoute =
  DashboardReportSalesFormReportByAdvocateIdRouteImport.update({
    id: '/report/salesFormReportByAdvocateId',
    path: '/report/salesFormReportByAdvocateId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportSalesFormReportBycategoryRoute =
  DashboardReportSalesFormReportBycategoryRouteImport.update({
    id: '/report/salesFormReportBycategory',
    path: '/report/salesFormReportBycategory',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsAllAdvocatesRoute =
  DashboardSettingsAllAdvocatesRouteImport.update({
    id: '/settings/allAdvocates',
    path: '/settings/allAdvocates',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsCreateUserRoute =
  DashboardSettingsCreateUserRouteImport.update({
    id: '/settings/createUser',
    path: '/settings/createUser',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsFormCategoryRoute =
  DashboardSettingsFormCategoryRouteImport.update({
    id: '/settings/formCategory',
    path: '/settings/formCategory',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/advocate/reportByDate': typeof DashboardAdvocateReportByDateRoute
  '/dashboard/advocate/reportByForm': typeof DashboardAdvocateReportByFormRoute
  '/dashboard/formSales/formSales': typeof DashboardFormSalesFormSalesRoute
  '/dashboard/formSales/formSalesReport': typeof DashboardFormSalesFormSalesReportRoute
  '/dashboard/report/salesFormReportByAdvocateId': typeof DashboardReportSalesFormReportByAdvocateIdRoute
  '/dashboard/report/salesFormReportBycategory': typeof DashboardReportSalesFormReportBycategoryRoute
  '/dashboard/settings/allAdvocates': typeof DashboardSettingsAllAdvocatesRoute
  '/dashboard/settings/createUser': typeof DashboardSettingsCreateUserRoute
  '/dashboard/settings/formCategory': typeof DashboardSettingsFormCategoryRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/advocate/reportByDate': typeof DashboardAdvocateReportByDateRoute
  '/dashboard/advocate/reportByForm': typeof DashboardAdvocateReportByFormRoute
  '/dashboard/formSales/formSales': typeof DashboardFormSalesFormSalesRoute
  '/dashboard/formSales/formSalesReport': typeof DashboardFormSalesFormSalesReportRoute
  '/dashboard/report/salesFormReportByAdvocateId': typeof DashboardReportSalesFormReportByAdvocateIdRoute
  '/dashboard/report/salesFormReportBycategory': typeof DashboardReportSalesFormReportBycategoryRoute
  '/dashboard/settings/allAdvocates': typeof DashboardSettingsAllAdvocatesRoute
  '/dashboard/settings/createUser': typeof DashboardSettingsCreateUserRoute
  '/dashboard/settings/formCategory': typeof DashboardSettingsFormCategoryRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/advocate/reportByDate': typeof DashboardAdvocateReportByDateRoute
  '/dashboard/advocate/reportByForm': typeof DashboardAdvocateReportByFormRoute
  '/dashboard/formSales/formSales': typeof DashboardFormSalesFormSalesRoute
  '/dashboard/formSales/formSalesReport': typeof DashboardFormSalesFormSalesReportRoute
  '/dashboard/report/salesFormReportByAdvocateId': typeof DashboardReportSalesFormReportByAdvocateIdRoute
  '/dashboard/report/salesFormReportBycategory': typeof DashboardReportSalesFormReportBycategoryRoute
  '/dashboard/settings/allAdvocates': typeof DashboardSettingsAllAdvocatesRoute
  '/dashboard/settings/createUser': typeof DashboardSettingsCreateUserRoute
  '/dashboard/settings/formCategory': typeof DashboardSettingsFormCategoryRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/advocate/reportByDate'
    | '/dashboard/advocate/reportByForm'
    | '/dashboard/formSales/formSales'
    | '/dashboard/formSales/formSalesReport'
    | '/dashboard/report/salesFormReportByAdvocateId'
    | '/dashboard/report/salesFormReportBycategory'
    | '/dashboard/settings/allAdvocates'
    | '/dashboard/settings/createUser'
    | '/dashboard/settings/formCategory'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/advocate/reportByDate'
    | '/dashboard/advocate/reportByForm'
    | '/dashboard/formSales/formSales'
    | '/dashboard/formSales/formSalesReport'
    | '/dashboard/report/salesFormReportByAdvocateId'
    | '/dashboard/report/salesFormReportBycategory'
    | '/dashboard/settings/allAdvocates'
    | '/dashboard/settings/createUser'
    | '/dashboard/settings/formCategory'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/advocate/reportByDate'
    | '/dashboard/advocate/reportByForm'
    | '/dashboard/formSales/formSales'
    | '/dashboard/formSales/formSalesReport'
    | '/dashboard/report/salesFormReportByAdvocateId'
    | '/dashboard/report/salesFormReportBycategory'
    | '/dashboard/settings/allAdvocates'
    | '/dashboard/settings/createUser'
    | '/dashboard/settings/formCategory'
    | '/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/advocate/reportByDate': {
      id: '/dashboard/advocate/reportByDate'
      path: '/advocate/reportByDate'
      fullPath: '/dashboard/advocate/reportByDate'
      preLoaderRoute: typeof DashboardAdvocateReportByDateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/advocate/reportByForm': {
      id: '/dashboard/advocate/reportByForm'
      path: '/advocate/reportByForm'
      fullPath: '/dashboard/advocate/reportByForm'
      preLoaderRoute: typeof DashboardAdvocateReportByFormRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/formSales/formSales': {
      id: '/dashboard/formSales/formSales'
      path: '/formSales/formSales'
      fullPath: '/dashboard/formSales/formSales'
      preLoaderRoute: typeof DashboardFormSalesFormSalesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/formSales/formSalesReport': {
      id: '/dashboard/formSales/formSalesReport'
      path: '/formSales/formSalesReport'
      fullPath: '/dashboard/formSales/formSalesReport'
      preLoaderRoute: typeof DashboardFormSalesFormSalesReportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/report/salesFormReportByAdvocateId': {
      id: '/dashboard/report/salesFormReportByAdvocateId'
      path: '/report/salesFormReportByAdvocateId'
      fullPath: '/dashboard/report/salesFormReportByAdvocateId'
      preLoaderRoute: typeof DashboardReportSalesFormReportByAdvocateIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/report/salesFormReportBycategory': {
      id: '/dashboard/report/salesFormReportBycategory'
      path: '/report/salesFormReportBycategory'
      fullPath: '/dashboard/report/salesFormReportBycategory'
      preLoaderRoute: typeof DashboardReportSalesFormReportBycategoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/allAdvocates': {
      id: '/dashboard/settings/allAdvocates'
      path: '/settings/allAdvocates'
      fullPath: '/dashboard/settings/allAdvocates'
      preLoaderRoute: typeof DashboardSettingsAllAdvocatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/createUser': {
      id: '/dashboard/settings/createUser'
      path: '/settings/createUser'
      fullPath: '/dashboard/settings/createUser'
      preLoaderRoute: typeof DashboardSettingsCreateUserRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/formCategory': {
      id: '/dashboard/settings/formCategory'
      path: '/settings/formCategory'
      fullPath: '/dashboard/settings/formCategory'
      preLoaderRoute: typeof DashboardSettingsFormCategoryRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdvocateReportByDateRoute: typeof DashboardAdvocateReportByDateRoute
  DashboardAdvocateReportByFormRoute: typeof DashboardAdvocateReportByFormRoute
  DashboardFormSalesFormSalesRoute: typeof DashboardFormSalesFormSalesRoute
  DashboardFormSalesFormSalesReportRoute: typeof DashboardFormSalesFormSalesReportRoute
  DashboardReportSalesFormReportByAdvocateIdRoute: typeof DashboardReportSalesFormReportByAdvocateIdRoute
  DashboardReportSalesFormReportBycategoryRoute: typeof DashboardReportSalesFormReportBycategoryRoute
  DashboardSettingsAllAdvocatesRoute: typeof DashboardSettingsAllAdvocatesRoute
  DashboardSettingsCreateUserRoute: typeof DashboardSettingsCreateUserRoute
  DashboardSettingsFormCategoryRoute: typeof DashboardSettingsFormCategoryRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdvocateReportByDateRoute: DashboardAdvocateReportByDateRoute,
  DashboardAdvocateReportByFormRoute: DashboardAdvocateReportByFormRoute,
  DashboardFormSalesFormSalesRoute: DashboardFormSalesFormSalesRoute,
  DashboardFormSalesFormSalesReportRoute:
    DashboardFormSalesFormSalesReportRoute,
  DashboardReportSalesFormReportByAdvocateIdRoute:
    DashboardReportSalesFormReportByAdvocateIdRoute,
  DashboardReportSalesFormReportBycategoryRoute:
    DashboardReportSalesFormReportBycategoryRoute,
  DashboardSettingsAllAdvocatesRoute: DashboardSettingsAllAdvocatesRoute,
  DashboardSettingsCreateUserRoute: DashboardSettingsCreateUserRoute,
  DashboardSettingsFormCategoryRoute: DashboardSettingsFormCategoryRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
